### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by WangHoHan** [WangHoHan/tonik#1]
- [x] Change selectors to be more specified
- [x] Check if next page exists (don't check if page size is per_page)
- [x] Cache latest query or init with sample data
- [x] Sorting options
- [x] Change per page elements (locally)
- [x]  Check if repositories init on page change
- [ ]  Introduce error page
- [x] Create unit and integration tests
- [x] Create README
